In [1]:
import numpy as np

In [3]:
np.random.randint(10, size=10)

array([8, 7, 1, 9, 7, 4, 0, 2, 6, 4])

In [4]:
a = np.random.randint(10, size=10)

In [5]:
a.ndim

1

In [6]:
a.shape

(10,)

In [7]:
a.size

10

In [8]:
a.dtype

dtype('int32')

In [11]:
b = np.random.randint(10, size = (3,5))
b

array([[8, 1, 1, 9, 5],
       [9, 2, 8, 1, 2],
       [6, 4, 6, 0, 8]])

In [12]:
b.ndim

2

In [13]:
b.size

15

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [18]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [20]:
x = np.array([1,2,3,99,99,3,2,1])

In [21]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [22]:
a,b,c = np.split(x,[3,5])

In [23]:
a

array([1, 2, 3])

In [24]:
b

array([99, 99])

In [25]:
c

array([3, 2, 1])

In [27]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [29]:
ust, alt = np.vsplit(m,[2])

In [30]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [31]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
sol,sag = np.hsplit(m,[2])

In [33]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [34]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [37]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [39]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [40]:
v = np.sort(v)
v

array([1, 2, 3, 4, 5])